name: vaitality
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  flutter_svg: 0.22.0
  mask_text_input_formatter: 2.0.0
  permission_handler: ^8.1.1
  flutter_reactive_ble: ^3.1.1+1
  dio: 4.0.0
  provider: 5.0.0
  syncfusion_flutter_gauges: 19.1.69
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

